### PR TITLE
OpenSim compatibility and other changes

### PR DESCRIPTION
**Pull request by Sei-Lisa**
OpenSim compatibility, reformat the scripts, add comments to the numeric codes in `[AV]sitA`, perform a few minor optimizations and bugfixes.

It also adds a Makefile, and instructions on how to create a release.

### CODE REVIEW

**Comment by codeviolet** [comment]
I quickly tested this branch in OpenSim. The core scripts compiled without issue, which is great, however they didn't pass testing in OpenSim. In Opensim, when pressing [HELPER], the helper rezzes but instantly jumps to 0,0,0 in the sim. I found this before when I tried to port the scripts to OpenSim a few weeks ago.

I think the reason the helper shoots to 0,0,0 in OpenSim is due to this line in the [AV]adjuster script:

```list details = llGetObjectDetails(llGetLinkKey(llGetLinkNumber()), [OBJECT_POS, OBJECT_ROT]);```

... which works in SL but does not work in OpenSim. And I suppose there may be other functions that do not work as expected in OpenSim, even though the scripts compile.

The changes in this PR are quite extensive so I wouldn't presume to merge this myself, although I think you should merge when you are confident that the commits achieve their intended purpose. The fact the scripts compile in OpenSim is great progress, and issues can be ironed out later.

**Comment by Sei-Lisa** [comment]
Hm, I tested in OpenSim .9.1.0 Dev (e9b7971: 2017-08-05 15:44:05 -0400) at Sandbox Plaza on OSgrid, and I didn't have such problems. I did a full basic setup with 2 animations and everything worked as expected, including the helper. What version of OpenSim did you test it on? Did you try that on a single prim, a root prim, or a child prim?

Would it make sense to require a minimum OpenSim version in order to be able to run AVsitter? I would think it would, as we can't aim to supporting each and every outdated version out there.

I'm wondering where the incompatibility resides exactly. It might be that `llGetLinkKey(0)` for single prims is broken, or that `llGetObjectDetails` applied to child prims returns local position, or something like that. I very much doubt that `llGetObjectDetails(id, [OBJECT_POS])` is broken. Knowing what's the exact problem here is important. If it's `llGetLinkKey`, there will be a lot of scripts affected.

Anyway, that function would need to be revisited. This line has the same effect as the one you've posted:

```lsl
list details = [llGetPos(), llGetRot()]
```

but of course, `llGetPos` and `llGetRot` can instead be directly used in place of `llList2Vector` and `llList2Rot` in the same function.

As for the commits, I've verified that the first three generate the same code after running it through the optimizer, except for `(str="")` within `strReplace`, which is clearly unnecessary. (I found and fixed a bug in the optimizer while verifying this, which caused it to miss some optimization opportunities.)

The bugfixes are all minor. The `llFrand` bugs can happen about once every 31-33 million times a channel number is generated. They can be verified to exist with the following code (remember the argument to `llFrand` is a float, so the integer is implicitly converted to float first):

```lsl
llOwnerSay((string)((integer)((float)999999999)));
llOwnerSay((string)((integer)((float)2147483646)));
```

This displays:

```
[16:38:45] Object: 1000000000
[16:38:45] Object: -2147483648
```

That commit should be fairly straightforward to check.

The last commit changes indentation only, but as I anticipated due to previous experience, the diff gets very messy. Still, it can be verified with the command-line Git using: `git log -p --ignore-space-change` (after fetching the commits from my repository and switching to my branch), by noting that there are no changes at all listed for that commit. I've done that.

For the other two commits ("Prepare the core scripts for OpenSim" and "Some micro-optimizations"), I hope not to have altered how the code works. The `else` removal in particular is an optimization I hope to include in the optimizer some time in the future.

The idea was to make a GitHub-only release after this PR, let it be tested out there and see if any bugs were introduced. I'm almost sure I did it right, but I may have missed something.

**Comment by Sei-Lisa** [comment]
Never mind about the OpenSim questions. I went to a sim in Kitely which uses OpenSim 0.8.1.0 and reproduced the issue. Indeed the bug is caused by using `llGetLinkKey(0)` in a single prim, which returns `NULL_KEY`. I'll check further uses of `llGetLinkKey` to see where else it may cause problems, and submit the corresponding fixes. In `[AV]adjuster` there are just two instances; the rest are safe.

**Comment by codeviolet** [comment]
Apologies I should have said, I was testing in Kitely. The sim I am testing in claims the sim version is "OpenSim 0.8.2.1 Post_Fixes". I agree, we should state a minimum OpenSim version (when we know what it is).

In Kitely, ```llGetLinkKey(0)``` seems to work for a single prim, but returns ```NULL_KEY``` when there are any linked prims, or an avatar is sitting. So if this is a bug in OpenSim 0.8.2.1 and fixed in future versions, then I think we don't need to do anything about it? What do you suggest? I'm not sure how often Kitely update their sim version.

All the other commits make good sense to me. Please merge when you are ready.

**Comment by Sei-Lisa** [comment]
Sorry, my analysis was wrong. In SL, the expected behaviour is that `llGetLinkKey` returns `NULL_KEY` for link number 0 when there's an avatar sitting, and the prim's key for link number 1 (and the avatar's key for link number 2). In 0.8.2.1, `llGetLinkKey` seems to work the same as in SL. The problem is that `llGetLinkNumber` returns 0 when there's an avatar sitting. That's what confused me.

In 0.9.0+, though, `llGetLinkNumber` still returns 0 when there's an avatar sitting, but `llGetLinkKey` expects 0 as the link number. Even worse, when there's an avatar sitting on a single prim, `llGetLinkKey` returns keys for links 0 and 2, but returns `NULL_KEY` for link 1. That difference with respect to SL might cause problems in some other parts of the code, so it has to be checked.

It would seem that the whole Kitely is 0.8.2.1, though. Maybe we can aim at making it work for that version as the minimum supported.

**Comment by Sei-Lisa** [comment]
I managed to make it work in OpenSim 0.8.2.1 with the above patch. Please test.

**Comment by Sei-Lisa** [comment]
Sorry, I forgot to include the generated scripts.

[AVsitter2-oss.zip](https://github.com/AVsitter/AVsitter/files/1236696/AVsitter2-oss.zip)

**Comment by codeviolet** [comment]
I have begun testing the zip you posted (in Kitely). Great progress. I will be working on porting some of the example furniture items to OpenSim to aid in further testing.

However, I did encounter an error when pressing [DUMP] while there are submenus in memory. I have included the error that I receive below. To replicate, either create a submenu via the menu, or include one in the notecard, then [DUMP].

With the following notecard:

```
POSE 1|ANIM_A
POSE 2|ANIM_C
TOMENU SUB1
MENU SUB1
POSE 3|ANIM_M
```

The results in chat when pressing [DUMP], including the script error is as follows:

```
[19:23] ◆--✄--COPY BELOW INTO "AVpos" NOTECARD--✄--
[19:23] ◆
[19:23] ◆"PRIMITIVE" AVsitter 2.2
[19:23] ◆
[19:23] ◆POSE 1|ANIM_A
[19:23] ◆POSE 2|ANIM_C
[19:23] Primitive: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: parsing '*|' - Quantifier {x,y} following nothing.
  at System.Text.RegularExpressions.RegexParser.ScanRegex () <0x403521d0 + 0x00711> in <filename unknown>:0 
  at System.Text.RegularExpressions.RegexParser.Parse (System.String re, RegexOptions op) <0x4034f7b0 + 0x000dd> in <filename unknown>:0 
  at System.Text.RegularExpressions.Regex..ctor (System.String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache) <0x4034ee30 + 0x0025a> in <filename unknown>:0 
  at System.Text.RegularExpressions.Regex..ctor (System.String pattern) <0x41569740 + 0x00039> in <filename unknown>:0 
  at OpenSim.Region.ScriptEngine.Shared.Api.OSSL_Api.osReplaceString (System.String src, System.String pattern, System.String replace, Int32 count, Int32 start) <0x407d8e90 + 0x0011c> in <filename unknown>:0 
  at OpenSim.Region.ScriptEngine.Shared.ScriptBase.Scrip
[19:23] Primitive: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: parsing '*|' - Quantifier {x,y} following nothing.
  at System.Text.RegularExpressions.RegexParser.ScanRegex () <0x403521d0 + 0x00711> in <filename unknown>:0 
  at System.Text.RegularExpressions.RegexParser.Parse (System.String re, RegexOptions op) <0x4034f7b0 + 0x000dd> in <filename unknown>:0 
  at System.Text.RegularExpressions.Regex..ctor (System.String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache) <0x4034ee30 + 0x0025a> in <filename unknown>:0 
  at System.Text.RegularExpressions.Regex..ctor (System.String pattern) <0x41569740 + 0x00039> in <filename unknown>:0 
  at OpenSim.Region.ScriptEngine.Shared.Api.OSSL_Api.osReplaceString (System.String src, System.String pattern, System.String replace, Int32 count, Int32 start) <0x407d8e90 + 0x0011c> in <filename unknown>:0 
  at OpenSim.Region.ScriptEngine.Shared.ScriptBase.Scrip
[19:23] ◆POSE 3|ANIM_M
[19:23] ◆
[19:23] ◆--✄--COPY ABOVE INTO "AVpos" NOTECARD--✄--
[19:23] ◆
```

The error seems to occur when the [90022](https://github.com/AVsitter/AVsitter/blob/master/AVsitter2/avsitter2_link_message_reference.md#90022) link message containing the MENU or TOMENU indicators is received by the [AV]adjuster script and processed by ```osReplaceString``` [here](https://github.com/AVsitter/AVsitter/blob/master/AVsitter2/%5BAV%5Dadjuster.lsl#L402). In such case the string sent in the link message is ```S:M:SUB1*|```. Perhaps that provides a clue. The error seems to be complaining about the string ending in ```*|``` but I am not sure.

**Comment by Sei-Lisa** [comment]
My bad. I didn't notice that `osReplaceString` requires a regular expression as search string. It chokes on the first `*` because that's a modifier to the previous element in a regex, and there's no previous element. The error message is a bit cryptic, but I guess that `*` is internally translated to `{0,}` (zero or more of the previous element) as they are equivalent, and that explains the `Quantifier {x,y} following nothing` error.

Undoing that OS-specific change suffices to go past that error. Let's hope the bugs of `llParseStringKeepNulls` are alleviated with the replacement of U+FFFD with U+001F. An alternative fix would be to go through every `strReplace` call and escape the strings as appropriate, but that's a lot of changes and needs to be kept in mind for the future, so this fix seems simpler. Another alternative fix would be to automatically escape search strings within `strReplace` to make them valid regexes, but I've looked into it and I didn't find a simple method.

Thanks a lot for the testing.

**Comment by Sei-Lisa** [comment]
Fix attached.

[AVsitter2-oss.zip](https://github.com/AVsitter/AVsitter/files/1242067/AVsitter2-oss.zip)

**Comment by Sei-Lisa** [comment]
Rebased on current master, as there was a conflict. The last two commits are new. Here's the updated version:

[AVsitter2-oss.zip](https://github.com/AVsitter/AVsitter/files/1254111/AVsitter2-oss.zip)

**Comment by Sei-Lisa** [comment]
Is there any outstanding issue left with OpenSim before merging this?

**Comment by codeviolet** [comment]
Yes, some minor issues encountered so far with testing the latest ```AVsitter2-oss.zip```:

**[AV]root-security.oss**

Assigning a new value to ```menu_channel``` within another function is causing a syntax error in the following line:

```
menu_handle = llListen(menu_channel = ((integer)llFrand(0x7FFFFF80) + 1) * -1, "", llGetOwner(), "");
```

**[AV]select.oss**

The following line is giving syntax error for similar reasons:
```
notecard_query = llGetNotecardLine(notecard_name, variable1 += 1);
```

This line of the script is not working as intended:

```
else if (llGetSubString(message, 0, 0) == "⊘" || (!select_type && llList2Integer(SYNCS, button_index) == FALSE && llList2Key(SITTERS, button_index) != NULL_KEY && llList2Key(SITTERS, button_index) != id))
```

It works ok when reverted to this, though I have not spotted the reason yet:

```
else if (llGetSubString(message, 0, 0) == "⊘" || ((!select_type) && llList2Integer(SYNCS, button_index) == FALSE && llList2Key(SITTERS, button_index) != NULL_KEY && llList2Key(SITTERS, button_index) != id))
```

**[AV]helper/[AV]adjuster.oss**

Clicking on the helper stick is not bringing up the menu. I wasn't sure if this is supposed to be fixed or not, seeing #21 remains open.

**Comment by Sei-Lisa** [comment]
Thank you very much for these notes. I misunderstood then, I thought these scripts were already working unchanged and I didn't bother checking.

The `(!select_type)` precedence issue is very disappointing. I thought only `~` was broken. I will need to check every parenthesis removal related to `!` then.

#21 affects also the SL version, that's why it isn't part of this PR. It is prominently visible for avatars whose UUID starts with numbers and also sitters other than sitter 0, which I guess is why it went undetected for several versions. It probably also affects cases where the controller and the sitter are different. It's awaiting for review. I presume that it will be correct if: (1) the sitter number in the stick is always valid, and (2) the order of sitter/controller is correct for the 90005 message. The documentation of that message seems to have them reversed, which made me less confident about the correctness of the fix.

**Comment by codeviolet** [comment]
No worries. I too misunderstood and expected the few syntax errors that I had manually corrected when testing in Kitely would somehow be 'automagically' dealt with by your makefile when you included these ancillary core scripts . I will do another round of testing after you link the next ```.zip``` file, to make sure everything's working as expected.

#21 had puzzled me, because I had only experienced the problem in OpenSim - not in SL. Thanks for the additional info, which helps to explain the confusion. I will see about testing #21 in SL and confirming the docs on that link message.

**Comment by Sei-Lisa** [comment]
Your SL avatars start with letters, making them take sitter 0. One of your OpenSim avatars starts with numbers, which is why you see it failing in OpenSim.

**Comment by Sei-Lisa** [comment]
Rebased on current master to pick up the fixes to the helper.

Latest file:
[AVsitter2-oss.zip](https://github.com/AVsitter/AVsitter/files/1260203/AVsitter2-oss.zip)

**Comment by SaraNyn** [comment]
What SL function exactly does osIsUUID replace in this branch? It might help me with a few things to know .......

**Comment by Sei-Lisa** [comment]
Rebased on current master to pick up the changes to `README.md` to add a section to it. The last four commits above are new.

**Comment by Sei-Lisa** [comment]
@SaraNyn, this SL code:

```lsl
if (key_var) ...
```

where `key_var` is a variable of type `key`, is equivalent to this OpenSim code:

```lsl
if (osIsUUID(key_var) && key_var != NULL_KEY)
```

In other words, it is only true if `key_var` is a valid key that isn't null. See <http://wiki.secondlife.com/wiki/If>, especially the table in the _Specification_ section.

**Comment by codeviolet** [comment]
After some testing today, I believe that the latest ```AVsitter2-oss.zip``` posted in this thread appears to fix the outstanding issues with the core scripts and I'll be glad to box up the initial OpenSim release.

**Comment by Sei-Lisa** [comment]
I'll be merging this PR then. Thank you very much for all your help with the OpenSim testing.

**Comment by codeviolet** [comment]
I think it would be good to offer an official boxed distribution in OpenSim (of the core scripts initially, with plugins perhaps included in a later update).  Should I await an official OpenSim release of the core scripts, or is it OK if I release a "beta" through Kitely market based on your most recent ```AVsitter2-oss.zip```?

**Comment by Sei-Lisa** [comment]
Sorry, I've been too busy to prepare a release. I hope to have some time tomorrow Friday.

**Comment by Sei-Lisa** [comment]
Would you please also check #33, which fixes a regression? It would be nice if it was included in the release.

**Comment by codeviolet** [comment]
No problem, and no rush. I just wasn't sure if you had plans to do a specific release of the core scripts release for OpenSim or not. I could proceed with releasing the core scripts on Kitely MP based on your last ```.zip```, and update them when there is a release.

**Pull request merged**
