### PR TITLE
Overhaul of settings.php

### PR DESCRIPTION
**Pull request by Sei-Lisa**
Fixes typo in table creation, and adds a number of improvements. See individual commits for details.

### CODE REVIEW

**Comment by codeviolet** [comment]
Wanting to incorporate your improvements, I have placed this version on my server as settings2.php (you can edit the adjust script and try it for testing purposes), but I receive errors like the following:

```"ERR02: Incorrect string value: '\xE2\x9C\x84--C...' for column 'text' at row 1"```

Easier to see the error if you add the following to the [AV]adjust script, of course:

```lsl
    http_response(key request_id, integer status, list metadata, string body){
        llOwnerSay(body);        
    }

```

**Comment by Sei-Lisa** [comment]
That's puzzling. In my installation it's working without problems. The error message is complaining about the scissors character, which is perfectly valid UTF-8. Did you call it with action=install? Does your MySQL version support utf8 encoding?

But this has reminded me of a caveat I had forgotten about: utf8 only supports up to 3-byte sequences (the first 65536 Unicode characters). For full support it needs to be utf8mb4. Sending a patch to correct it.

**Comment by codeviolet** [comment]
my bad, I hadn't called action=install so it was using the old schema. It's all working now and I have the latest version running live on avsitter.com/settings.php, tested with a large multi-sitter notecard but please notify if any users report difficulties. I will merge this soon if nothing else comes up beforehand.

**Comment by Sei-Lisa** [comment]
Great! In order to port the data from the old table to the new (assuming you kept a backup or renamed the table), this should suffice:

```sql
INSERT INTO new_table SELECT * FROM old_table;
SELECT MAX(id)+1 FROM new_table;
-- look at the value and then do:
ALTER TABLE new_table AUTO_INCREMENT=(result of previous query);
```

**Comment by codeviolet** [comment]
Thanks for the sql advice :) It was a good chance to drop old records. From the old records, I've kept only those linked to by the old q&a site.

**Pull request merged**
