### PR TITLE
adding settings.php and Noob-detector.lsl per #20

### PR DESCRIPTION
**Pull request by codeviolet**
If the developers think the noob-detector is beneficial for assisting others with their builds, then it can be included in future releases

### CODE REVIEW

**Comment by codeviolet** [comment]
I am still learning GitHub, and really intended both these commits to be combined as one. At this stage, do I have any options to merge them together before submitting this PR?

**Comment by Sei-Lisa** [comment]
Thank you very much for donating this code as well! Some comments:

### settings.php

- It looks good to me security wise. The only issue I see is that in case of abuse, you can't blame the avatar, because a malicious user could forge the headers from the outside.
  - The only solution I can think of, is to check the IP range, see <http://wiki.secondlife.com/wiki/Simulator_IP_Addresses>. Just in case there's some unlisted IP range, the originating IP address of the update calls would need to be added to the database in order to allow the user to notify us. That should not raise any privacy concerns, since it's supposed to be a sim IP, not a user's, and these are assigned at random every restart.
- For future proofing, I'd like to make some changes to the escaping scheme, so that there's no need to track which variables are escaped and which ones aren't.
- It can't deal with out-of-order updates. I wonder if that has been a primary cause of occasional failures which have been reported.
- An index on `(keep, timestamp)` could potentially speed up searches; it depends on whether the number of records is small enough as to fit into the server's memory or not.
- For the benefit of users, I'd place something like `$allow_install = false;` as a global at the beginning, rather than using `1==2`.
- At the top level, `$GLOBALS['email_from']` and `$email_from` are the same. I'd suggest to use the latter at the top for clarity, together with a brief explanation of what they are used for. For example: `// These email addresses are used to report incidences.`
- Question: Is there a reason to not auto-clean records with `keep=1` as well, just with a different expiry time? What's the use of keeping records indefinitely?
- Question: Is there a reason to output `text/html` rather than `text/plain`?

Some of these changes can be made after the initial merge, but I'd suggest the `$allow_install` and `$email_from` changes to be present from the start (see below).

### Noob-detector.lsl

It has the same problem as the other scripts did with the channel number: the number 2147483646.0 is not a single-precision float, therefore it is rounded to the closest one, which is 2147483648.0.  It is probably safe anyway, as it should never return the last number and the closest one is 2147483520.0, but to stay safe, it's best to replace `2147483646` with `0x7FFFFF80`.

It looks good otherwise, but my review hasn't been too thorough.

### Amending commits with `git`

Squashing is a bit difficult to do, and I'm not a fan of doing that automatically. For this case, I'd suggest to delete the last commit and amend the previous one. Here's how, assuming the only two commits in that branch are the ones above:

```
# Ensure we're working on the correct branch:
git checkout settings-php

# If the above command complains about local changes, use this
# to save them temporarily:
#git stash

# The following makes the branch pointer go 1 commit back,
# effectively deleting the last commit, but it keeps the changes in all
# files as uncommitted changes, i.e. it does not touch the working
# directory.
git reset HEAD~1

# Do any other changes you need. If there are new files, you can
# add them now.
#git add xxx yyy

# Amend the last commit (which is now the first of the two above).
# The -v flag allows you to review the diff of what will be committed,
# under the comment section of the commit message, while editing.
# The -a flag adds all changed files to the (in this case amended)
# commit. You have the chance to edit the commit message as well
# (I'm assuming you're using an editor to edit the commit messages).
git commit --amend -va

# Force-push the branch, to publish the changes on the PR.
# Note that in GitHub this will move all commits under the last
# comment, but that's OK.
git push -f origin settings-php

# If you stashed the changes before, go to the correct branch if
# necessary and recover them back with this:
#git checkout <branch>
#git stash pop
```

I'm experiencing a GitHub bug where if you kept the PR page open while force-pushing, it shows the old and new commits until you refresh it, but it's a visual glitch only.

One side note: please avoid force-pushing to the master branch of the *main* repository. Force-pushing to a branch in your repository is fine. I guess you have no reason, it's just a comment :)

**Comment by codeviolet** [comment]
I have amended the commit per your instructions, and it seems to have worked :)

* I have made your suggested changes to ```$allow_install``` and ```$email_from```, etc.

* Changed from ```text/html``` to ```text/plain```, seeing I never implemented any HTML beautification to the output.

* I have added the ability to filter by IP, but have it switched off as it would prevent ```settings.php``` from being usable in OpenSim. I don't suppose it viable to know all the address ranges of all the OpenSim worlds.

* Some records are used as links in the old [Q&A](https://avsitter.com/qa) and so should be kept indefinitely. That's all the ```keep``` flag is being used for now. If settings.php links were ever used in documentation or forums again then the script could perhaps be modified to keep based on the ```HTTP_REFERER``` from which the record is accessed.

* Right, it can not deal with http requests being received out of order. However an equal likely cause of reported failures would be complete http timeout (the server restarting, or temporary outbound http glitch in SL). In my experience it's more likely that some data is simply not being received, rather than being received out of order. lsl-side error checking would require more complex code in the [AV]adjuster, and the ability to halt the dump and resend data in the event of a timeout. This would be complex, and preferably avoided IMO, so I suggest that users should let us know how often it's not working, so that developers can decide if something more needs to be done.

**Comment by Sei-Lisa** [comment]
Thank you, all good now. It's interesting that out-of-order reception is less common than occasional failures. I'll try to modify my inworld-only server to take that into account.

About OpenSim, I wonder whether to have something like separate `settings.php` and `settings-os.php` so that the SL one uses IP ranges.

**Pull request merged**
