### PR TITLE
Improve OpenSim-friendliness.

### PR DESCRIPTION
**Pull request by Sei-Lisa**
OpenSim has problems with the precedence of `~`, so change some I've found.

It also has trouble with assignments in expressions, so change all I've found

### CODE REVIEW

**Comment by Sei-Lisa** [comment]
Aside from the compilation problem fixed in this issue, [AV]faces seems to work fine in OpenSim. Could it be included in the OpenSim distribution?

**Comment by Sei-Lisa** [comment]
Currently, most scripts compile in OpenSim. Only the plugins from AVcontrol are missing. I imagine the answer is no, but just in case, is there an Xcite for OpenSim?

[AVsitter2-oss.zip](https://github.com/AVsitter/AVsitter/files/1439248/AVsitter2-oss.zip)

**Comment by Sei-Lisa** [comment]
@Anthonyghub please check the MLP converter in the above zip. It will probably have the same problem as in #45 though.

**Comment by Anthonyghub** [comment]
Hello Sei-Lisa. I have tested AVpos-shifter, Missing-anim-finder, MLP-converter and also Avprop plugin and they all work fine! Thanks! :)

**Comment by Anthonyghub** [comment]
hello Sei. I have seen that in POSE (in single poses), it's possible to have only 9 animations in menu and the arrow doesn't appear to go to next page of menu to show other animations (animation number 10 isn't shown). Meanwhile in SYNC the arrow to go to next page is shown correctly. Could you help please to fix this? Thanks

**Comment by Sei-Lisa** [comment]
I can't reproduce it. Do you have any plugins? Can you give a basic AVpos example notecard which fails?

**Comment by Anthonyghub** [comment]
Hello Sei. I have sent you inword notecard on osgrid. I have seen that if a leave only the single POSE in AVpos notecard, it will give the possibile to go in page 2 to menu; meanwhile if there are other voices in menu like in the notecard that i have send you it won't shot the possibility to go to page 2 with arrows in single POSE.

**Comment by Sei-Lisa** [comment]
I still don't see a problem.

avsitter-menu-10-animations

Are you using any plugins?

**Comment by Sei-Lisa** [comment]
Never mind, I forgot to drop another pair of scripts. I see the problem in the Female menu only; I'm looking into it.

**Comment by Sei-Lisa** [comment]
@Anthonyghub, using `[AV]sitA.oss` and `[AV]sitB.oss` in the above zip fixed the issue for me. Please update.

For the record, the commit that fixed this is f599fb8, which is scary. I'm trying to look into why.

**Comment by Sei-Lisa** [comment]
OK, cause identified. This is the change that fixed it:

```diff
@@ -134,9 +118,10 @@ integer animation_menu(integer animation_menu_function)
         }
         integer total_items;
         integer i = current_menu + 1;
-        while (i++ < llGetListLength(MENU_LIST) && llSubStringIndex(llList2String(MENU_LIST, i), "M:"))
+        while (i < llGetListLength(MENU_LIST) && llSubStringIndex(llList2String(MENU_LIST, i), "M:"))
         {
             ++total_items;
+            ++i;
         }
         list menu_items0;
         list menu_items2;
```

Note how the original version depends on right-to-left LSL evaluation order: i is incremented on the left side of the `&&` but it is expected to NOT be incremented on the right side (having a menu after the last pose was important to reproduce it, which is why I couldn't reproduce it in my attempts, because I didn't add more menus).

I spotted that during my eyeballing of potential optimizations and changed it, to make it more robust (as it has proven to be), given that it would expand the script by just about 1 byte.

**Comment by Anthonyghub** [comment]
Hello @Sei-Lisa ! Have you already made a release of the AV Sitter files with these fixes? Could you send me a copy of these files inworld? So i test them. Thanks

**Comment by Sei-Lisa** [comment]
No, there is no release yet. However, the same zip that contains the extra scripts also contains the fix. It's in the third comment of this thread.

**Pull request merged**
