### PR TITLE
Adjustments needed in AVcontrol plugin for OpenSim

### PR DESCRIPTION
**Pull request by ft-**
A few minor adjustments needed to make these acceptable on OpenSim's XEngine.
you only need commit 5eb99570134d7f3bbbd7f743a4146fefcb8793d4.
Just another info: my fork OpenSim/Arriba supports AVsitter since May 2018.

### CODE REVIEW

**Comment by ft-** [comment]
you only need commit 5eb99570134d7f3bbbd7f743a4146fefcb8793d4.
Just another info: my fork OpenSim/Arriba supports AVsitter since May 2018.

**Comment by Sei-Lisa** [comment]
Thanks for calling our attention on those. We prefer the assignment to remain in its place, just wrap it in parentheses to make OpenSim happy. That saves code memory in SL. See this commit as an example:

https://github.com/AVsitter/AVsitter/commit/467cbf8b6bccccbc6c9fc6591677ed617e84ec55

Also, this PR needs to be rebased, to keep the history tidy. Furthermore, please submit it from a dedicated branch, not from `master`, as that will prevent future problems if you need to submit more pull requests. That will mean that this PR will need to be closed.

If you don't care whether the commit that fixes it is made by you or not, please let me know and I will take care of it. But if you want to appear as the author of the commit, and you aren't sure what changes are necessary, please let me know and I'll try to explain how to submit the PR from a branch and keep it up to date. It seems that you've merged a PR on your own in your fork. I encourage you to do these things in a separate branch, while keeping `master` in sync with upstream, to avoid problems like adding extraneous commits to the PR as it happened here. You can then just rebase your branch when you want to incorporate the latest changes.

**Comment by ft-** [comment]
It is a minor change as such so not much of work was in it at all. So no problem with applying that one under your name. Actually what happened is that my local copy happened to be sitting on codeviolet/avsitter before. It was overlooked by me and triggered that merge thing. Submitting PRs from branch is just the same action ;)

**Comment by ft-** [comment]
However, if I hit something like that next time I created a new branch on my fork repo to ensure that it is not messed up that way again. git pull url <src-branch>:<dest-branch>is just helpful ;)

**Comment by ft-** [comment]
Dang have to cleanup the whole git repo because master branch rebuild is remote rejected. So I am going to recreate this pull request afterwards.

**Comment by Sei-Lisa** [comment]
> By the way, do you happen to know that you can set author on commits? ;)

Yes, or I could just have cherry-picked it if it used the preferred fix. If I rewrite it, the best way to deal with it IMO is mentioning the original author or reporter in the commit message. Committing something with the name of a different author without even having their approval sounds like awful etiquette :)

The new one does it right so no need to worry about this. I'll take care of it tomorrow. The commit message title is still too long though.

> Dang have to cleanup the whole git repo because master branch rebuild is remote rejected.

Yes, I saw you'd have an issue with your local copy's master, which would have taken some git-fu to repair (basically, `git fetch upstream`, `git checkout upstream/master` and then `git branch -f master` to move the branch pointer to the correct commit, then `git checkout master`, create a new branch and redo the patch, assuming you have this repo as upstream).

**Pull request closed without merging**
